# Generated by Django 5.2.8 on 2025-11-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Paris Plantes', max_length=100)),
                ('site_description', models.TextField(default='Plateforme de paris sur la durée de vie des plantes')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('starting_points', models.IntegerField(default=1000, verbose_name='Points de départ')),
                ('min_bet_amount', models.IntegerField(default=10, verbose_name='Mise minimum')),
                ('max_bet_amount', models.IntegerField(default=500, verbose_name='Mise maximum')),
                ('exact_multiplier', models.FloatField(default=5.0, verbose_name='Multiplicateur exact (±1 jour)')),
                ('close_multiplier', models.FloatField(default=3.0, verbose_name='Multiplicateur proche (±3 jours)')),
                ('approximate_multiplier', models.FloatField(default=1.5, verbose_name='Multiplicateur approximatif (±7 jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_registered', 'Utilisateur inscrit'), ('plant_added', 'Plante ajoutée'), ('bet_placed', 'Pari placé'), ('plant_died', 'Plante morte'), ('bet_resolved', 'Pari résolu'), ('rank_changed', 'Classement changé')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Biographie')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('total_points_cache', models.IntegerField(default=1000, verbose_name='Points totaux')),
                ('rank_cache', models.IntegerField(default=0, verbose_name='Classement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('bet_won', 'Pari gagné'), ('bet_lost', 'Pari perdu'), ('plant_died', 'Plante morte'), ('new_rank', 'Nouveau classement'), ('system', 'Message système'), ('reminder', 'Rappel')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='core_notifi_user_id_bd535f_idx')],
            },
        ),
    ]
